app/models.py
import datetime

from flask.ext.login import UserMixin
from flask.ext.security import RoleMixin
from . import db, bcrypt


class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=80, unique=True)
    description = db.StringField(max_length=255)


class User(db.Document, UserMixin):
    email = db.EmailField(max_length=255, unique=True)
    _password = db.StringField(max_length=255)
    active = db.BooleanField(default=True)
    confirmed_at = db.DateTimeField(default=datetime.now())
    roles = db.ListField(db.ReferenceField(Role), default=[])

    @property
    def password(self):
        return self._password

    @password.setter
    def _set_password(self, plaintext):
        self._password = bcrypt.generate_password_hash(plaintext)

app/forms/__init__.py
from flask.ext.wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import DataRequired


class RedirectForm(Form):
    url = StringField('URL', validators=[DataRequired('Required')])
    submit = SubmitField('Go')

app/__init__.py
# import sys
# sys.path.insert(0, '/Users/jrienton/.virtualenvs/utils-py/lib/python3.5/site-packages')

from flask import Flask
from flask_bootstrap import Bootstrap
from .home import home as home_blueprint

app = Flask(__name__, instance_relative_config=True)
app.config.from_object('config.default')
app.config.from_pyfile('config.py', silent=True)

bootstrap = Bootstrap(app)

# Load blueprints (if any)
app.register_blueprint(home_blueprint)

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views, errors

app/home/views.py
import pycurl
from flask import render_template
from io import BytesIO
from . import home
from ..forms import RedirectForm

headers = {}
buffer = BytesIO()
b = ''


@home.route('/301notnier/index', methods=['GET', 'POST'])
def index():
    global buffer
    buffer = BytesIO()
    h=''
    form = RedirectForm()
    if form.validate_on_submit():
        get_headers(form.url.data, buffer)
        return render_template('home/index.html', form=form, headers=headers, h=b.replace('\r\n', '<br/>'))
    return render_template('home/index.html', form=form)


def get_headers(url, buffer=None):
    global b
    b = ''
    try:
        curl = pycurl.Curl()
        curl.setopt(pycurl.URL, url)
        curl.setopt(pycurl.FOLLOWLOCATION, True)
        curl.setopt(pycurl.AUTOREFERER, True)
        curl.setopt(pycurl.HEADER, True)
        curl.setopt(pycurl.NOBODY, True)
        curl.setopt(pycurl.WRITEFUNCTION, buffer.write)
        curl.setopt(pycurl.HEADERFUNCTION, header_function)
        curl.setopt(pycurl.USERAGENT, 'Mozilla/5.0 (compatible; pycurl)')
        curl.perform()
        b = buffer.getvalue().decode('utf-8')
        # curl.getinfo()
        curl.close()
    except:
        pass


def header_function(header_line):
    # HTTP standard specifies that headers are encoded in iso-8859-1.
    # On Python 2, decoding step can be skipped.
    # On Python 3, decoding step is required.
    header_line = header_line.decode('iso-8859-1')

    # Header lines include the first status line (HTTP/1.x ...).
    # We are going to ignore all lines that don't have a colon in them.
    # This will botch headers that are split on multiple lines...
    if ':' not in header_line:
        return

    # Break the header line into header name and value.
    name, value = header_line.split(':', 1)

    # Remove whitespace that may be present.
    # Header lines include the trailing newline, and there may be whitespace
    # around the colon.
    name = name.strip()
    value = value.strip()

    # Header names are case insensitive.
    # Lowercase name here.
    name = name.lower()

    # Now we can actually record the header name and value.
    headers[name] = value

app/templates/home/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    {{ super() }}
    <div class="container">
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <div class="jumbotron">
            <h2>301 Redirect Test</h2>

            <form action="{{ url_for('home.index') }}" method="post">
                {{ form.url(class_='form-control', placeholder='URL', required='required') }}
                <br>
                {{ form.submit(class_='btn btn-info') }}
                {{ form.csrf_token }}
            </form>
        </div>
        <hr/>
        <div class="row">
            {{  h|safe }}
        </div>
{#        <div class="row">#}
{#            {% for name in headers %}#}
{#                <li class="form-control">#}
{#                    {{ name }}: {{ headers[name] }}#}
{#                </li>#}
{#            {% endfor %}#}
{#        </div>#}
    </div>
{% endblock %}

app/templates/layout.html
{% extends 'bootstrap/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% block content %}
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('home.index') }}">Home</a></li>
                    <li><a href="#">About</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>